"""Runtime capability registry — schema-driven matching, no hardcoded keyword tables."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from .models import Capability


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------

def _core_platform_dir() -> Path:
    """Resolve core-platform root from env or file location."""
    env = os.environ.get("MAOMIAI_CORE_PLATFORM_DIR")
    if env:
        return Path(env).expanduser().resolve()
    return Path(__file__).resolve().parents[4]


def _schema_registry_path() -> Path:
    """Path to the external capability registry JSON."""
    return _core_platform_dir() / "data" / "agent_policy" / "capability_registry.json"


def _runtime_registry_path() -> Path:
    """Path to the runtime capability registry (persisted edits)."""
    root = _core_platform_dir() / "data" / "capability_registry"
    root.mkdir(parents=True, exist_ok=True)
    return root / "capabilities.json"


def _builtin_modules_path() -> Path:
    """Path to the own builtin fusion modules JSON."""
    return _core_platform_dir() / "data" / "skill_brain" / "our_builtin_skill_modules.json"


def _default_skills_path() -> Path:
    """Path to the default skills JSON generated by skill-brain."""
    return _core_platform_dir() / "data" / "skill_brain" / "default_skills.json"


def _skill_state_path() -> Path:
    """Path to the skill lifecycle state JSON."""
    return _core_platform_dir() / "data" / "skill_brain" / "skill_state.json"


# ---------------------------------------------------------------------------
# Skill lifecycle state
# ---------------------------------------------------------------------------

def load_skill_state() -> dict[str, Any]:
    """Load skill lifecycle state from skill_state.json."""
    path = _skill_state_path()
    if not path.exists():
        return {"version": "missing", "skills": {}}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {"version": "invalid", "skills": {}}
    if not isinstance(payload.get("skills"), dict):
        payload["skills"] = {}
    return payload


def save_skill_state(state: dict[str, Any]) -> None:
    """Persist skill lifecycle state to skill_state.json."""
    path = _skill_state_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")


def get_skill_state(skill_id: str) -> dict[str, Any]:
    """Return lifecycle state for a single skill."""
    state = load_skill_state()
    item = state.get("skills", {}).get(skill_id)
    return item if isinstance(item, dict) else {}


def set_skill_enabled(skill_id: str, enabled: bool) -> dict[str, Any]:
    """Enable or disable a skill and update its lifecycle label."""
    from datetime import datetime, timezone
    state = load_skill_state()
    skills = state.setdefault("skills", {})
    item = skills.setdefault(skill_id, {})
    item["enabled"] = bool(enabled)
    item["lifecycle"] = "enabled" if enabled else "disabled"
    item["updated_at"] = datetime.now(timezone.utc).isoformat()
    save_skill_state(state)
    return item


def set_skill_pinned(skill_id: str, pinned: bool) -> dict[str, Any]:
    """Pin or unpin a skill (pinned skills get a ranking boost)."""
    from datetime import datetime, timezone
    state = load_skill_state()
    skills = state.setdefault("skills", {})
    item = skills.setdefault(skill_id, {})
    item["pinned"] = bool(pinned)
    item["updated_at"] = datetime.now(timezone.utc).isoformat()
    save_skill_state(state)
    return item


def record_skill_usage(skill_id: str) -> dict[str, Any]:
    """Increment usage count and update last_used_at for a skill."""
    from datetime import datetime, timezone
    state = load_skill_state()
    skills = state.setdefault("skills", {})
    item = skills.setdefault(skill_id, {})
    item["usage_count"] = int(item.get("usage_count") or 0) + 1
    item["last_used_at"] = datetime.now(timezone.utc).isoformat()
    save_skill_state(state)
    return item


# ---------------------------------------------------------------------------
# Default skills loader
# ---------------------------------------------------------------------------

def load_default_skills() -> list[dict[str, Any]]:
    """Load enabled default skills from skill_brain/default_skills.json."""
    path = _default_skills_path()
    if not path.exists():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    skills = payload.get("skills", [])
    return [x for x in skills if isinstance(x, dict) and x.get("enabled_by_default", True)]


def load_builtin_modules() -> list[dict[str, Any]]:
    """Load own builtin fusion modules from skill_brain/our_builtin_skill_modules.json."""
    path = _builtin_modules_path()
    if not path.exists():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    modules = payload.get("modules", [])
    return [x for x in modules if isinstance(x, dict)]


def _builtin_contracts_path() -> Path:
    """Path to the builtin execution contracts JSON."""
    return _core_platform_dir() / "data" / "skill_brain" / "builtin_execution_contracts.json"


def load_builtin_contracts() -> dict[str, dict[str, Any]]:
    """Load builtin execution contracts keyed by module id."""
    path = _builtin_contracts_path()
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    contracts = payload.get("contracts", [])
    if not isinstance(contracts, list):
        return {}
    return {
        str(item.get("id")): item
        for item in contracts
        if isinstance(item, dict) and item.get("id")
    }


def _builtin_module_to_capability(module: dict[str, Any]) -> dict[str, Any]:
    """Convert a builtin fusion module into a capability dict (id prefix builtin.*).

    Since C26-R5 the returned dict includes the full execution contract:
    execution_contract, execution_mode, allowed_tools, input_schema,
    output_schema, acceptance_tests, runtime_dependency_policy.
    """
    module_id = str(module.get("id") or "").strip()
    title = str(module.get("title") or module_id).strip()
    merged = [str(x) for x in module.get("merged_capabilities", []) or []]
    plan = [str(x) for x in module.get("implementation_plan", []) or []]
    contract = load_builtin_contracts().get(module_id, {})
    tags: list[str] = []
    for ref in module.get("source_references", []) or []:
        for tag in ref.get("tags", []) or []:
            if tag not in tags:
                tags.append(str(tag))
    description = "；".join(merged[:6])
    allowed_tools = contract.get("allowed_tools") or [
        "capability.match",
        "repo_memory.search",
        "model.generate",
    ]
    return {
        "id": module_id,
        "name": title,
        "type": "own_builtin_module",
        "description": description,
        "runtime": "builtin_fusion",
        "target": "capability.match",
        "priority": 80,
        "enabled": True,
        "tags": tags,
        "input_schema": contract.get("input_schema") or {},
        "metadata": {
            "source_type": "own_builtin_module",
            "builtin": True,
            "builtin_priority": 1.0,
            "implementation_status": contract.get("implementation_status", module.get("implementation_status", "planned")),
            "source_reference_count": module.get("source_reference_count", 0),
            "merged_capabilities": merged,
            "implementation_plan": plan,
            "skill_tags": tags,
            "tools": allowed_tools,
            "risk": "safe",
            "execution_contract": contract,
            "execution_mode": contract.get("execution_mode"),
            "allowed_tools": allowed_tools,
            "output_schema": contract.get("output_schema"),
            "acceptance_tests": contract.get("acceptance_tests", []),
            "runtime_dependency_policy": contract.get("runtime_dependency_policy", "owned_code_only"),
        },
    }


def _skill_to_capability(skill: dict[str, Any]) -> dict[str, Any]:
    """Convert a default skill dict into a capability dict (id prefix skill.*).

    Merges lifecycle state from skill_state.json so that disabled/pinned/usage
    information flows into the capability registry.
    """
    skill_id = str(skill.get("id") or "").strip()
    title = str(skill.get("title") or skill_id).strip()
    description = str(skill.get("description") or "").strip()
    tags = [str(x) for x in skill.get("tags", []) or []]
    tools = [str(x) for x in skill.get("tools", []) or []] or [
        "repo_memory.search", "capability.match", "model.generate"
    ]
    # Merge lifecycle state
    lstate = get_skill_state(skill_id)
    enabled = bool(lstate.get("enabled", skill.get("enabled_by_default", True)))
    pinned = bool(lstate.get("pinned", False))
    usage_count = int(lstate.get("usage_count") or 0)
    rating = lstate.get("rating")
    lifecycle = lstate.get("lifecycle", "enabled" if enabled else "disabled")
    return {
        "id": f"skill.{skill_id}",
        "name": title,
        "type": "default_skill",
        "description": description,
        "runtime": "skill_brain",
        "target": "capability.match",
        "priority": 40,
        "enabled": enabled,
        "tags": tags,
        "input_schema": {},
        "metadata": {
            "source_type": "default_skill",
            "source_path": skill.get("source_path"),
            "source_repo": skill.get("source_repo"),
            "html_url": skill.get("html_url"),
            "skill_tags": tags,
            "tools": tools,
            "risk": str(skill.get("risk") or "safe"),
            "language": skill.get("language"),
            "stars": skill.get("stars"),
            "original_tags": skill.get("original_tags", []),
            "buckets": skill.get("buckets", []),
            "lifecycle": lifecycle,
            "pinned": pinned,
            "usage_count": usage_count,
            "rating": rating,
        },
    }


# ---------------------------------------------------------------------------
# External schema loader
# ---------------------------------------------------------------------------

def load_capability_schema() -> Dict[str, Any]:
    """Load the external capability_registry.json schema."""
    path = _schema_registry_path()
    if not path.exists():
        return {"version": "missing", "capabilities": []}
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Tokenisation / term extraction
# ---------------------------------------------------------------------------

def _terms(value: str) -> set[str]:
    """Extract search terms from a string — CJK n-gram aware."""
    text = str(value or "").lower()
    tokens: set[str] = set()
    current: list[str] = []
    for ch in text:
        if ch.isalnum() or ch in {"_", "-", "."}:
            current.append(ch)
        else:
            if current:
                tokens.add("".join(current))
                current = []
    if current:
        tokens.add("".join(current))
    # CJK n-grams for Chinese/Japanese/Korean text
    compact = "".join(ch for ch in str(value or "") if not ch.isspace())
    for n in (2, 3, 4):
        for i in range(max(0, len(compact) - n + 1)):
            tokens.add(compact[i:i + n].lower())
    return {x for x in tokens if x}


def _capability_text(capability: dict[str, Any]) -> str:
    """Collect all descriptive text from a capability dict for term matching."""
    parts: list[str] = []
    for key in ("id", "name", "type", "description", "runtime", "target"):
        if capability.get(key):
            parts.append(str(capability.get(key)))
    for item in capability.get("tags", []) or []:
        parts.append(str(item))
    for item in capability.get("aliases", []) or []:
        parts.append(str(item))
    return " ".join(parts)


# ---------------------------------------------------------------------------
# Capability loading — merge schema + runtime overrides
# ---------------------------------------------------------------------------

_DEFAULT_CAPABILITIES: Optional[List[Capability]] = None


def _capabilities_from_schema() -> List[Capability]:
    """Build Capability objects from the external schema."""
    schema = load_capability_schema()
    caps: List[Capability] = []
    for entry in schema.get("capabilities", []):
        try:
            caps.append(Capability(
                id=entry["id"],
                name=entry.get("name", entry["id"]),
                type=entry.get("type", "model"),
                description=entry.get("description", ""),
                runtime=entry.get("runtime", "model"),
                target=entry.get("target", ""),
                priority=entry.get("priority", 50),
                enabled=entry.get("enabled", True),
                tags=entry.get("tags", []),
                metadata=entry.get("metadata", {}),
            ))
        except Exception:
            continue
    return caps


def load_capabilities() -> List[Capability]:
    """Load capabilities: runtime overrides if present, else schema."""
    global _DEFAULT_CAPABILITIES
    runtime_path = _runtime_registry_path()
    if runtime_path.exists():
        try:
            data = json.loads(runtime_path.read_text(encoding="utf-8"))
            return [Capability.model_validate(item) for item in data]
        except Exception:
            pass
    # Fallback to schema
    caps = _capabilities_from_schema()
    if caps:
        _DEFAULT_CAPABILITIES = caps
        return caps
    # Last resort: empty list
    return []


def ensure_registry() -> None:
    """Create runtime registry file when missing (from schema)."""
    caps = load_capabilities()
    if caps and not _runtime_registry_path().exists():
        save_capabilities(caps)


def list_capabilities(enabled_only: bool = False) -> List[dict]:
    """Return capability dictionaries for API responses.

    Includes schema/runtime capabilities, own builtin modules (builtin.*),
    and default skills (skill.*).  Builtin modules are listed before
    external-reference skills so that planners prefer owned implementations.
    """
    items = load_capabilities()
    if enabled_only:
        items = [item for item in items if item.enabled]
    result = [item.model_dump() for item in items]
    existing_ids = {str(x.get("id")) for x in result}
    # Own builtin modules are added before external-reference skills.
    for module in load_builtin_modules():
        cap = _builtin_module_to_capability(module)
        if cap.get("id") not in existing_ids:
            result.append(cap)
            existing_ids.add(str(cap.get("id")))
    # Append default skills that are not already present and not disabled
    for skill in load_default_skills():
        cap = _skill_to_capability(skill)
        if not cap.get("enabled", True):
            continue
        if cap.get("id") not in existing_ids:
            result.append(cap)
            existing_ids.add(str(cap.get("id")))
    return result


def get_capability(capability_id: str) -> Optional[Capability]:
    """Return one capability by id."""
    for item in load_capabilities():
        if item.id == capability_id:
            return item
    return None


def save_capabilities(items: List[Capability]) -> None:
    """Persist runtime capability registry."""
    path = _runtime_registry_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps([item.model_dump() for item in items], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def upsert_capability(capability: Capability) -> Capability:
    """Insert or replace one capability."""
    items = load_capabilities()
    for index, item in enumerate(items):
        if item.id == capability.id:
            items[index] = capability
            save_capabilities(items)
            return capability
    items.append(capability)
    save_capabilities(items)
    return capability


# ---------------------------------------------------------------------------
# Schema-driven matching — no hardcoded keyword tables
# ---------------------------------------------------------------------------

def match_capabilities(
    query: str,
    intent: str | None = None,
    tags: list[str] | None = None,
    limit: int = 5,
) -> List[Capability]:
    """Match a query to enabled capabilities using schema text overlap scoring.

    Scoring is based on term overlap between the query and the combined
    descriptive text of each capability (id, name, type, description,
    tags, aliases).  No hardcoded Chinese keyword tables are used.

    Default skills (skill.*) are also included in matching.
    """
    tags = tags or []
    query_terms = _terms(query)
    if not query_terms:
        return []

    # Build the full candidate pool: schema/runtime + builtin modules + default skills
    all_caps: list[Capability] = list(load_capabilities())

    existing_ids = {c.id for c in all_caps}

    # Add own builtin modules before external-reference skills
    for module in load_builtin_modules():
        cap_dict = _builtin_module_to_capability(module)
        if cap_dict.get("id") not in existing_ids:
            try:
                all_caps.append(Capability(**cap_dict))
                existing_ids.add(str(cap_dict.get("id")))
            except Exception:
                continue

    # Add default skills as Capability objects
    for skill in load_default_skills():
        cap_dict = _skill_to_capability(skill)
        if cap_dict.get("id") not in existing_ids:
            try:
                all_caps.append(Capability(**cap_dict))
                existing_ids.add(str(cap_dict.get("id")))
            except Exception:
                continue

    # Load schema to get aliases for scoring
    schema = load_capability_schema()
    alias_map: Dict[str, set[str]] = {}
    for entry in schema.get("capabilities", []):
        cap_id = entry.get("id", "")
        entry_terms: set[str] = set()
        for item in entry.get("aliases", []) or []:
            entry_terms.update(_terms(str(item)))
        for item in entry.get("tags", []) or []:
            entry_terms.update(_terms(str(item)))
        alias_map[cap_id] = entry_terms

    # Also add skill aliases from skill metadata.original_tags
    for skill in load_default_skills():
        cap_id = f"skill.{skill.get('id', '')}"
        skill_terms: set[str] = set()
        for item in skill.get("tags", []) or []:
            skill_terms.update(_terms(str(item)))
        for item in skill.get("original_tags", []) or []:
            skill_terms.update(_terms(str(item)))
        if cap_id not in alias_map:
            alias_map[cap_id] = skill_terms
        else:
            alias_map[cap_id].update(skill_terms)

    # Also add builtin module aliases from merged_capabilities and skill_tags
    for module in load_builtin_modules():
        cap_id = module.get("id", "")
        mod_terms: set[str] = set()
        for item in module.get("merged_capabilities", []) or []:
            mod_terms.update(_terms(str(item)))
        for ref in module.get("source_references", []) or []:
            for tag in ref.get("tags", []) or []:
                mod_terms.update(_terms(str(tag)))
        if cap_id not in alias_map:
            alias_map[cap_id] = mod_terms
        else:
            alias_map[cap_id].update(mod_terms)

    scored: list[tuple[float, Capability]] = []
    for capability in all_caps:
        if not capability.enabled:
            continue
        # Build text from capability fields
        cap_text = " ".join([
            capability.id,
            capability.name,
            capability.type,
            capability.description,
            " ".join(capability.tags),
            capability.runtime,
            capability.target,
        ])
        cap_terms = _terms(cap_text)
        # Merge schema alias terms
        cap_terms.update(alias_map.get(capability.id, set()))

        # Compute overlap score
        overlap = query_terms.intersection(cap_terms)
        base_score = len(overlap) / max(1, min(len(query_terms), len(cap_terms)))

        # Bonus for explicit tag match
        tag_bonus = 0.0
        for tag in tags:
            if tag in capability.tags:
                tag_bonus += 0.1

        # Bonus for intent match
        intent_bonus = 0.0
        if intent:
            intent_terms = _terms(intent)
            if intent_terms.intersection(cap_terms):
                intent_bonus = 0.15

        # Small priority-based tiebreaker (0..1 range, max ~1.0)
        priority_bonus = capability.priority / 1000.0

        score = round(base_score + tag_bonus + intent_bonus + priority_bonus, 4)

        # Prefer owned builtin modules over external-reference skills.
        meta = capability.metadata or {}
        if meta.get("builtin"):
            score += 0.12

        # Lifecycle boosts: pinned, usage, rating
        if meta.get("pinned"):
            score += 0.08
        usage_count = int(meta.get("usage_count") or 0)
        if usage_count > 0:
            score += min(0.05, usage_count * 0.005)
        rating_val = meta.get("rating")
        try:
            if rating_val is not None:
                score += max(0.0, min(0.05, float(rating_val) / 100.0))
        except (TypeError, ValueError):
            pass
        score = round(score, 4)

        if score > 0:
            scored.append((score, capability))

    scored.sort(key=lambda item: item[0], reverse=True)
    return [item[1] for item in scored[:limit]]
